text = open('textnum2', 'r')
content = text.read()
print('Содержимое файла:',content)
text = open('textnum2', 'r')
content = text.readlines()
print('Количество строк в файле', len(content))
text = open('textnum2', 'r')
content = text.read()
content = content.split(' ')
print('Количество слов:',len(content))
text.close()